sudo: false

language: node_js

node_js:
  - "lts/*"

install: npm install

services:
  - mongodb

before_script:
  - "sleep 15"
  - "mongo test --eval 'db.addUser("test", "test");'"

script: 
  - npm run test

after_script: npm run coverage